
import random
from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi

app = FastAPI()


facts: list[str]

with open("./facts.txt", "r") as f:
    facts = f.readlines()


@app.get("/{id}")
def get_fact_by_id(id: int):
    '''
    Fact about snakes
    '''
    return {"id": id, "fact": facts[id].strip()}


@app.get("/random")
def get_random_fact():
    '''
    Free random fact about snakes
    '''
    id = random.randint(0, len(facts) - 1)
    return {"id": id, "fact": facts[id].strip()}


def custom_openapi():
    if app.openapi_schema:
        return app.openapi_schema
    openapi_schema = get_openapi(
        title="Snake Facts API",
        version="1.0.0",
        description="The data was generated by chatGTP",
        routes=app.routes,
    )
    openapi_schema["info"]["x-logo"] = {
        "url": "https://fastapi.tiangolo.com/img/logo-margin/logo-teal.png"
    }
    app.openapi_schema = openapi_schema
    return app.openapi_schema


app.openapi = custom_openapi
